name: React App CI/CD with Bun

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2  # Configura o Buildx (se precisar do BuildKit)

  #     - name: Install Bun
  #       run: |
  #         curl -fsSL https://bun.sh/install | bash
  #         echo "$HOME/.bun/bin" >> $GITHUB_PATH  # Adiciona Bun ao PATH

  #     - name: Install dependencies
  #       run: bun install --frozen-lockfile

  #     - name: Build the app
  #       run: bun run build

  #     - name: Save build artifacts
  #       uses: actions/upload-artifact@v4
  #       with:
  #         name: build-output
  #         path: build/

  # docker-push:
  #   runs-on: ubuntu-latest
  #   needs: build

    # steps:
    #   - name: Download build artifacts
    #     uses: actions/download-artifact@v4
    #     with:
    #       name: build-output
    #       path: build/

      - name: Build Docker image
        run: |
          docker build -t f5sites/lojasdomago_react .

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker image
        run: docker push f5sites/lojasdomago_react

  # deploy:
  #   runs-on: ubuntu-latest
  #   needs: build

  #   steps:
  #     - name: Download build artifacts
  #       uses: actions/download-artifact@v4
  #       with:
  #         name: build-output
  #         path: build/

  #     - name: Deploy to GitHub Pages
  #       uses: JamesIves/github-pages-deploy-action@v4
  #       with:
  #         branch: gh-pages
  #         folder: build
  #         token: ${{ secrets.GITHUB_TOKEN }}
